Algoritmo "exercicio"

Var
nota1,nota2,soma,multi,op:inteiro
Inicio
 escreval ( "entre com nota1" )
leia (nota1)
escreval ("entre com nota2")
leia (nota2)
escreval ("escreva a opcao")
leia (op)
se (op=0) entao
soma<- nota1 + nota2
 escreval("o resultado da soma e:", soma)
 senao
 se (op=1) entao
 multi<- nota1 * nota2
  escreval("o resultado da multiplicacao e:", multi)
senao
 escreval("essa opcao nao existe" )
 fimse
 fimse
Fimalgoritmo