Algoritmo "exercicio"

Var
nota1,nota2,nota3,nota4,media:real
Inicio
leia (nota1)
 escreval ( " entre com nota1 " )
leia (nota2)
 escreval ( " entre com nota2 " )
leia (nota3)
 escreval ( " entre com nota3 " )
leia (nota4)
 escreval ( " entre com nota4 " )
media <- (nota1 + nota2 + nota3 + nota4 ) / 4;
se(media>=6) entao
  escreval("o aluno esta aprovado(a)")
  senao
  escreval("o aluno esta reprovado(a)")
  fimse
Fimalgoritmo